version: "3.9"
services:
  # NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      # Only build develop stage from Dockerfile
      target: develop
    # Mount our host dir to the docker container
    # Mount api directory (./api) to (:) docker container (/src/app)
    # Reflect File changes from host to container
    volumes:
      - ./api:/src/app
      - /src/app/node_modules/
    # Run in dev mode: npm run start:dev
    command: npm run start:debug
    depends_on: 
      - mongo
    environment:
      DATABASE_URL: ${DATABASE_URL}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECRET}
      PORT: ${NEST_PORT}
    ports:
      - ${NEST_PORT}:${NEST_PORT}
      - 9229:9229
  
  # Angular admin
  admin:
    build:
      dockerfile: Dockerfile
      context: ./admin
      target: develop
    command: npm run start
    volumes:
      - ./admin:/admin/src/app
      - /admin/src/app/node_modules
    ports:
      - ${ANGULAR_PORT}:${ANGULAR_PORT}
    links:
      - api

  # mongo db service
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  # mongo db express service for GUI
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}
