@userId = 643c04fb51bdef2188ce9c07
@hostname = localhost
@port = 3000
@baseUrl = http://{{hostname}}:{{port}}/api
@contentType = application/json
@createdAt = {{$datetime iso8601}}
@modifiedBy = {{$processEnv USERNAME}}
@TOKEN = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJha2VzaC5zb2ppdHJhQHZpaXRvci5jbG91ZCIsInN1YiI6IjY0MzI2ZjkxYzE5Njg4Y2MxODA1NzZkMiIsImlhdCI6MTY4MTAzMDY0NSwiZXhwIjoxNjgxMDY2NjQ1fQ.IXg6vxM4XM_hvzZiV0IbHBW7IZWVD3G8c0ES4JVyHX4

# get all users
GET {{baseUrl}}/user HTTP/1.1
Authorization: {{TOKEN}}

###
# get user by id
GET {{baseUrl}}/user/{{userId}} HTTP/1.1
Authorization: {{TOKEN}}

###
# update user by id
PATCH {{baseUrl}}/user/{{userId}} HTTP/1.1
Authorization: {{TOKEN}}
Content-Type: {{contentType}}

{
    "email": "john@example.com"
}

###
# create user
POST {{baseUrl}}/user HTTP/1.1
Authorization: {{TOKEN}}
Content-Type: {{contentType}}

{
    "name": "Rakesh Sojitra",
    "email": "rakesh.sojitra@viitor.cloud",
    "password": "Test@123"
}

###
# Delete user by Id
DELETE {{baseUrl}}/user/{{userId}} HTTP/1.1
Authorization: {{TOKEN}}

###
# login api
POST {{baseUrl}}/auth/login HTTP/1.1
Content-Type: {{contentType}}

{
    "email": "rakesh.sojitra@viitor.cloud",
    "password": "Test@123"
}
